name: build firmware

on: [push, pull_request, workflow_dispatch]

include:
  - board: nice_nano
    shield: temper_left nice_view_adapter nice_view
  - board: nice_nano
    shield: temper_right nice_view_adapter nice_view
    
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
